#!/usr/bin/env python3
"""Generate `Zeta23/ThmD/Sextuple/A1275/TreeWords.lean` (two-level packed layout).

Inputs (canonical, exact):
  * `macro-scalar-tree/manifest.json`      — token/leaf counts and stream SHA-256 values;
  * `macro-scalar-tree/topology-u64le.bin` — 20 three-bit tokens per little-endian u64 word.

The 31 `WordData/LeafBlocksNNN.lean` modules (25 block words of 256 leaf words each, the
last with 4) are frozen inputs and are not regenerated; they are only referenced.

Layout emitted:
  * `improvedTopologyBlocks : Array (Array Nat)` — the topology words in blocks of
    `improvedTopologyBlockSize = 140` (138 blocks, the last with 119 words);
  * `improvedLeafBlockGroups : Array (Array Nat)` — the 31 `WordData` arrays.
Two-level arrays keep every kernel array lookup short (≤ 140 + 138 list steps instead of
up to 19,299), which is what makes the 8,953 chunk replays cheap.

Optional `--frozen` cross-check: the flat word list must equal the literal in the frozen
single-level `TreeWords.lean` (SHA-256 `ca120e6b…` in the source freeze).
No `assert`: every admission check raises.
"""
from __future__ import annotations
import argparse, hashlib, json, re, sys
from pathlib import Path

BLOCK = 140
GROUPS = 31
WORDS_PER_TOKEN_WORD = 20


def require(cond: bool, msg: str) -> None:
    if not cond:
        raise SystemExit(f"gen_a1275_blocked_words: {msg}")


def read_words(tree_dir: Path) -> tuple[int, int, list[int]]:
    manifest = json.loads((tree_dir / "manifest.json").read_text())
    raw = (tree_dir / "topology-u64le.bin").read_bytes()
    require(hashlib.sha256(raw).hexdigest() == manifest["stream_sha256"]["topology"],
            "topology stream SHA-256 mismatch against manifest.json")
    require(len(raw) % 8 == 0, "topology stream length not a multiple of 8")
    words = [int.from_bytes(raw[i:i + 8], "little") for i in range(0, len(raw), 8)]
    token_count = int(manifest["leaves"]) * 2 - 1
    require(token_count == 385967, f"unexpected token count {token_count}")
    require(len(words) == (token_count + 19) // 20, "topology word count mismatch")
    require(all(w < 2 ** 60 for w in words), "topology word exceeds 60 bits")
    rem = token_count % 20
    require(rem == 0 or words[-1] < 2 ** (3 * rem), "nonzero topology padding")
    return token_count, int(manifest["leaves"]), words


def frozen_words(path: Path) -> list[int]:
    src = path.read_text()
    key = "def improvedTopologyWords : Array Nat := #["
    i = src.index(key) + len(key)
    j = src.index("]", i)
    return [int(x) for x in re.findall(r"\d+", src[i:j])]


def render(token_count: int, leaf_count: int, words: list[int]) -> str:
    blocks = [words[i:i + BLOCK] for i in range(0, len(words), BLOCK)]
    out = []
    out.append("import Zeta23.ThmD.Sextuple.A1275.TreeReader")
    out.append("import Zeta23.ThmD.Sextuple.AffineTree")
    for g in range(GROUPS):
        out.append(f"import Zeta23.ThmD.Sextuple.A1275.WordData.LeafBlocks{g:03d}")
    out.append("")
    out.append("/-!")
    out.append("# Packed words of the `A = 51/4000` certificate tree (two-level layout)")
    out.append("")
    out.append(f"Generated by `certificates/sextuple/a1275/tools/gen_a1275_blocked_words.py` from the")
    out.append("canonical `certificates/sextuple/a1275/macro-scalar-tree/` streams.")
    out.append("")
    out.append(f"* topology: `{token_count}` three-bit tokens, `20` per `60`-bit word, `{len(words)}` words")
    out.append(f"  stored in `{len(blocks)}` blocks of `{BLOCK}` words (the last has `{len(blocks[-1])}`);")
    out.append(f"* leaves: `{leaf_count}` `321`-bit leaf words, `256` per block word, `754` block words")
    out.append(f"  stored in the `{GROUPS}` `WordData` groups of `25` block words (the last has `4`).")
    out.append("")
    out.append("The two-level arrays make every kernel array lookup short; `Layout.lean` proves the")
    out.append("audited flat layout predicates for the concatenations and `TreeReader.lean` shows the")
    out.append("two-level readers agree with the audited flat readers.")
    out.append("-/")
    out.append("")
    out.append("noncomputable section")
    out.append("namespace Zeta23.ThmD.Sextuple.MacroPrototype")
    out.append("open Zeta23.ThmD.Sextuple")
    out.append("")
    out.append(f"def improvedTokenCount : ℕ := {token_count}")
    out.append(f"def improvedLeafCount : ℕ := {leaf_count}")
    out.append("")
    out.append("set_option maxRecDepth 100000 in")
    out.append("def improvedTopologyBlocks : Array (Array Nat) := #[")
    for bi, b in enumerate(blocks):
        out.append("  #[" + ", ".join(str(w) for w in b) + "]" + ("," if bi < len(blocks) - 1 else ""))
    out.append("]")
    out.append("")
    out.append("def improvedLeafBlockGroups : Array (Array Nat) := #[")
    for g in range(GROUPS):
        out.append(f"  improvedLeafBlocksChunk{g:03d}" + ("," if g < GROUPS - 1 else ""))
    out.append("]")
    out.append("")
    out.append("def improvedTopologyStream : CursorStream AffineTreeToken :=")
    out.append("  blockedTopologyStream improvedTokenCount improvedTopologyBlockSize improvedTopologyBlocks")
    out.append("")
    out.append("def improvedPayloadStream : CursorStream (AffineLeafPayload (MacroScalarLeaf 272 1383)) :=")
    out.append("  groupedLeafStream improvedLeafCount improvedLeafBlockGroups")
    out.append("")
    out.append("def improvedRootBox : GapBox := initialGapBox 59")
    out.append("")
    out.append("end Zeta23.ThmD.Sextuple.MacroPrototype")
    out.append("end")
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tree-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    ap.add_argument("--frozen", type=Path, default=None, help="frozen flat TreeWords.lean to cross-check")
    ap.add_argument("--report", type=Path, default=None)
    a = ap.parse_args()
    token_count, leaf_count, words = read_words(a.tree_dir)
    if a.frozen is not None:
        require(frozen_words(a.frozen) == words, "flat words differ from the frozen TreeWords.lean literal")
    text = render(token_count, leaf_count, words)
    a.out.write_text(text)
    digest = hashlib.sha256(text.encode()).hexdigest()
    if a.report is not None:
        a.report.write_text(json.dumps({
            "output": str(a.out), "output_sha256": digest, "output_bytes": len(text.encode()),
            "token_count": token_count, "leaf_count": leaf_count, "word_count": len(words),
            "block_size": BLOCK, "block_count": (len(words) + BLOCK - 1) // BLOCK,
            "leaf_groups": GROUPS, "frozen_cross_check": a.frozen is not None,
            "generator_sha256": hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
        }, indent=1, sort_keys=True) + "\n")
    print(f"wrote {a.out} sha256={digest} words={len(words)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
